-- ===== Authors =====
INSERT INTO author (name) VALUES ('J.K. Rowling');
INSERT INTO author (name) VALUES ('George R.R. Martin');
INSERT INTO author (name) VALUES ('J.R.R. Tolkien');
INSERT INTO author (name) VALUES ('Jane Austen');
INSERT INTO author (name) VALUES ('Agatha Christie');
INSERT INTO author (name) VALUES ('Dan Brown');
INSERT INTO author (name) VALUES ('Stephen King');
INSERT INTO author (name) VALUES ('Isaac Asimov');
INSERT INTO author (name) VALUES ('Mark Twain');
INSERT INTO author (name) VALUES ('Ernest Hemingway');

-- ===== Publishers =====
INSERT INTO publisher (name) VALUES ('Bloomsbury');
INSERT INTO publisher (name) VALUES ('Bantam Books');
INSERT INTO publisher (name) VALUES ('HarperCollins');
INSERT INTO publisher (name) VALUES ('Penguin');
INSERT INTO publisher (name) VALUES ('Simon & Schuster');
INSERT INTO publisher (name) VALUES ('Random House');
INSERT INTO publisher (name) VALUES ('Scholastic');
INSERT INTO publisher (name) VALUES ('Vintage Books');
INSERT INTO publisher (name) VALUES ('Scribner');
INSERT INTO publisher (name) VALUES ('Orbit Books');

-- ===== Books =====
INSERT INTO book (title, price, author_id, publisher_id) VALUES ('Harry Potter 1', 19.99, 1, 1);
INSERT INTO book (title, price, author_id, publisher_id) VALUES ('Harry Potter 2', 20.99, 1, 2);
INSERT INTO book (title, price, author_id, publisher_id) VALUES ('Harry Potter 3', 21.99, 1, 3);
INSERT INTO book (title, price, author_id, publisher_id) VALUES ('Game of Thrones 1', 25.99, 2, 1);
INSERT INTO book (title, price, author_id, publisher_id) VALUES ('Game of Thrones 2', 27.99, 2, 3);
INSERT INTO book (title, price, author_id, publisher_id) VALUES ('The Hobbit', 15.99, 3, 3);
INSERT INTO book (title, price, author_id, publisher_id) VALUES ('LOTR: Fellowship', 16.99, 3, 5);
INSERT INTO book (title, price, author_id, publisher_id) VALUES ('Pride and Prejudice', 12.99, 4, 4);
INSERT INTO book (title, price, author_id, publisher_id) VALUES ('Emma', 13.99, 4, 10);
INSERT INTO book (title, price, author_id, publisher_id) VALUES ('Murder on the Orient Express', 14.99, 5, 5);
INSERT INTO book (title, price, author_id, publisher_id) VALUES ('Death on the Nile', 14.50, 5, 5);
INSERT INTO book (title, price, author_id, publisher_id) VALUES ('The Da Vinci Code', 18.99, 6, 6);
INSERT INTO book (title, price, author_id, publisher_id) VALUES ('Angels and Demons', 18.50, 6, 6);
INSERT INTO book (title, price, author_id, publisher_id) VALUES ('The Shining', 22.99, 7, 7);
INSERT INTO book (title, price, author_id, publisher_id) VALUES ('It', 23.99, 7, 7);
INSERT INTO book (title, price, author_id, publisher_id) VALUES ('Foundation', 17.99, 8, 8);
INSERT INTO book (title, price, author_id, publisher_id) VALUES ('I, Robot', 16.49, 8, 8);
INSERT INTO book (title, price, author_id, publisher_id) VALUES ('Tom Sawyer', 10.99, 9, 9);
INSERT INTO book (title, price, author_id, publisher_id) VALUES ('Huckleberry Finn', 11.99, 9, 6);
INSERT INTO book (title, price, author_id, publisher_id) VALUES ('The Old Man and the Sea', 13.50, 10, 1);
INSERT INTO book (title, price, author_id, publisher_id) VALUES ('For Whom the Bell Tolls', 14.75, 10, 3 );
INSERT INTO book (title, price, author_id, publisher_id) VALUES ('Harry Potter 4', 22.99, 1, 1);
INSERT INTO book (title, price, author_id, publisher_id) VALUES ('Harry Potter 5', 23.99, 1, 1);
INSERT INTO book (title, price, author_id, publisher_id) VALUES ('Harry Potter 6', 24.99, 1, 1);
INSERT INTO book (title, price, author_id, publisher_id) VALUES ('Harry Potter 7', 25.99, 1, 1);
INSERT INTO book (title, price, author_id, publisher_id) VALUES ('Game of Thrones 3', 28.99, 2, 2);
INSERT INTO book (title, price, author_id, publisher_id) VALUES ('Game of Thrones 4', 29.99, 2, 2);
INSERT INTO book (title, price, author_id, publisher_id) VALUES ('LOTR: Two Towers', 17.99, 3, 3);
INSERT INTO book (title, price, author_id, publisher_id) VALUES ('LOTR: Return of the King', 18.99, 3, 3);
INSERT INTO book (title, price, author_id, publisher_id) VALUES ('Sense and Sensibility', 14.49, 4, 4);
INSERT INTO book (title, price, author_id, publisher_id) VALUES ('Northanger Abbey', 13.75, 4, 4);
INSERT INTO book (title, price, author_id, publisher_id) VALUES ('The ABC Murders', 14.20, 5, 5);
INSERT INTO book (title, price, author_id, publisher_id) VALUES ('And Then There Were None', 14.90, 5, 5);
INSERT INTO book (title, price, author_id, publisher_id) VALUES ('Inferno', 19.25, 6, 6);
INSERT INTO book (title, price, author_id, publisher_id) VALUES ('Origin', 20.00, 6, 6);
INSERT INTO book (title, price, author_id, publisher_id) VALUES ('Carrie', 21.99, 7, 7);
INSERT INTO book (title, price, author_id, publisher_id) VALUES ('Misery', 22.99, 7, 7);
INSERT INTO book (title, price, author_id, publisher_id) VALUES ('The Caves of Steel', 15.50, 8, 8);
INSERT INTO book (title, price, author_id, publisher_id) VALUES ('The Naked Sun', 16.00, 8, 8);
INSERT INTO book (title, price, author_id, publisher_id) VALUES ('Life on the Mississippi', 12.99, 9, 9);
INSERT INTO book (title, price, author_id, publisher_id) VALUES ('A Connecticut Yankee...', 13.99, 9, 9);
INSERT INTO book (title, price, author_id, publisher_id) VALUES ('A Farewell to Arms', 14.49, 10, 10);
INSERT INTO book (title, price, author_id, publisher_id) VALUES ('The Sun Also Rises', 14.89, 10, 10);
INSERT INTO book (title, price, author_id, publisher_id) VALUES ('The Casual Vacancy', 19.00, 1, 1);
INSERT INTO book (title, price, author_id, publisher_id) VALUES ('Fantastic Beasts', 18.50, 1, 1);
INSERT INTO book (title, price, author_id, publisher_id) VALUES ('The Winds of Winter', 30.00, 2, 2);
INSERT INTO book (title, price, author_id, publisher_id) VALUES ('Dreamsongs', 26.99, 2, 2);
INSERT INTO book (title, price, author_id, publisher_id) VALUES ('The Silmarillion', 19.50, 3, 3);
